--- #YAML:1.0
name:                Config-Simple-Inherit
version:             0.04
abstract:            Inherit values from, overwrite a base configuration
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Config::Simple:                0
    Data::Dumper:                  0
    Test:                          0
    Test::Deep:                    0
    Test::More:                    0
    Text::ParseWords:              0
    UNIVERSAL:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Hugh Esco <hesco@campaignfoundations.com>
